# Generated by Django 4.1.2 on 2023-03-20 02:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(db_index=True, default='Anonymus', max_length=14, verbose_name='Name')),
                ('adhar_num', models.CharField(max_length=255, verbose_name='Adhar Number')),
                ('dob', models.CharField(max_length=255, verbose_name='Date of Birth')),
                ('identification_mark', models.CharField(max_length=255, verbose_name='Identification Mark')),
                ('category', models.CharField(max_length=25, verbose_name='Category')),
                ('height', models.CharField(max_length=255, verbose_name='Height')),
                ('weight', models.CharField(max_length=255, verbose_name='Weight')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone_num', models.CharField(max_length=255, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=550, verbose_name='Address')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father Name')),
                ('father_adhar_num', models.CharField(max_length=255, verbose_name='Father Adhar Number')),
                ('father_phone_num', models.CharField(max_length=255, verbose_name='Father Phone Number')),
                ('father_qualification', models.CharField(max_length=255, verbose_name='Father Qualification')),
                ('father_profession', models.CharField(max_length=255, verbose_name='Father Profession')),
                ('father_designation', models.CharField(max_length=255, verbose_name='Father Designation')),
                ('father_email', models.CharField(max_length=255, verbose_name='Father Email')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother Name')),
                ('mother_adhar_num', models.CharField(max_length=255, verbose_name='Mother Adhar Number')),
                ('mother_phone_num', models.CharField(max_length=255, verbose_name='Mother Phone Number')),
                ('mother_qualification', models.CharField(max_length=255, verbose_name='Mother Qualification')),
                ('mother_profession', models.CharField(max_length=255, verbose_name='Mother Profession')),
                ('mother_designation', models.CharField(max_length=255, verbose_name='Mother Designation')),
                ('mother_email', models.CharField(max_length=255, verbose_name='Mother Email')),
                ('random_num', models.AutoField(primary_key=True, serialize=False, verbose_name='Random Number')),
                ('Student_class', models.CharField(max_length=12, verbose_name='Class')),
                ('section', models.CharField(max_length=12, verbose_name='Section')),
                ('doj', models.CharField(max_length=255, verbose_name='Date of Join')),
                ('document', cloudinary.models.CloudinaryField(blank=True, db_index=True, max_length=255, verbose_name='Documents')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
